language: python

python:
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"

install:
  - pip install -q $DJANGO
  - pip install coveralls
  - python setup.py -q install

before_script:
  - rm -rf build

script:
  - coverage run --source=registration setup.py test

after_success:
  - coveralls --verbose
